# Generated by Django 4.2.22 on 2025-10-24 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("endpoints", "0002_endpoint_cache_age_seconds"),
    ]

    operations = [
        migrations.AddField(
            model_name="endpoint",
            name="is_materialized",
            field=models.BooleanField(
                default=False, help_text="Whether this endpoint's query results are materialized to S3"
            ),
        ),
        migrations.AddField(
            model_name="endpoint",
            name="materialized_query",
            field=models.ForeignKey(
                blank=True,
                help_text="The underlying materialized view that backs this endpoint",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="endpoints",
                to="posthog.datawarehousesavedquery",
            ),
        ),
        migrations.AddIndex(
            model_name="endpoint",
            index=models.Index(fields=["team", "is_materialized"], name="endpoint_team_mat_idx"),
        ),
    ]
